class McpServerProvider
  def self.available_servers
    # Stub implementation - in the future, this will be generated by another part of the app
    [
      {
        name: "Test MCP Server",
        url: "http://localhost:3001/mcp",
        description: "A test MCP server for development"
      }
    ]
  end
  
  def self.get_server_by_name(name)
    available_servers.find { |server| server[:name] == name }
  end
end
